baseURL = "https://example.com"
languageCode = "en-us"
title = "Diber"


# CSS Plugins
#[[params.plugins.css]]
#link = "plugins/fontawesome/css/all.min.css"

# Js Plugins
#[[params.plugins.js]]
#link = "plugins/mixitup/mixitup.min.js"
#[[params.plugins.js]]
#link = "plugins/slick/slick/slick.min.js"

[menu]

	[[menu.main]]
		identifier = "home"
		name = "home"
		url = "/"
		weight = 2

	[[menu.main]]
		identifier = "articles"
		name = "articles"
		url = "/articles/"
		weight = 1


